# Generated by Django 4.2 on 2023-06-19 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorites',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
