# Generated by Django 4.1.1 on 2023-04-20 07:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("favorites", "0001_initial"),
        ("records", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="favorites",
            name="record",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="records.record"
            ),
        ),
        migrations.AddField(
            model_name="favorites",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterUniqueTogether(
            name="favorites",
            unique_together={("user", "record")},
        ),
    ]
