# Generated by Django 4.2 on 2023-06-21 20:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0005_remove_changerequest_processo_changerequest_acordao_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('favorites', '0002_alter_favorites_description'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favorites',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='favorites',
            name='acordao',
            field=models.ForeignKey(default='526af892-c877-4ddb-9992-1aacb51c36d6', on_delete=django.db.models.deletion.CASCADE, to='records.acordao'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='favorites',
            unique_together={('user', 'acordao')},
        ),
        migrations.RemoveField(
            model_name='favorites',
            name='processo',
        ),
    ]