# Generated by Django 4.2 on 2023-06-14 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChangeRequestManager',
        ),
    ]