# Generated by Django 4.2 on 2023-06-21 19:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_field_record_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acordao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        )
    ]