# cat 0003_alter_changedrecord_id.py
# Generated by Django 4.2 on 2023-06-08 16:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_alter_record_added_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changedrecord',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]