# Generated by Django 4.2 on 2023-06-21 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_acordao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='processo',
        ),
        migrations.AddField(
            model_name='record',
            name='acordao',
            field=models.ForeignKey(default='a3ec0052-8df8-4f20-83b3-d6b8d84c46a9', on_delete=django.db.models.deletion.CASCADE, to='records.acordao'),
            preserve_default=False,
        ),
    ]